import type { Metadata } from "next";
import "../globals.css";

import { Menu } from "lucide-react";
import Link from "next/link";
import { ThemeProvider } from "@/components/theme-provider";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  // DropdownMenuLabel,
  // DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Separator } from "@/components/ui/separator";
import { cn } from "@/lib/utils";
import { limelight, zenKakuGothicNew, inconsolata } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="jp"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        // "font-sans",
        zenKakuGothicNew.variable,
        inconsolata.variable,
      )} //, inter.variable)}
    >
      <body
        className={cn(
          "min-h-full flex flex-col",
          // "bg-white dark:bg-black",
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div
            className={cn("h-screen flex-1 flex flex-col", limelight.className)}
          >
            <header className="TopBar flex flex-col h-12.5 w-full sticky top-0 bg-(--color-background)">
              <div className={cn("flex flex-1 p-2")}>
                <Link href="/" className="flex items-center">
                  <div className="flex font-bold text-2xl text-center justify-center px-2">
                    Limbre.net
                  </div>
                </Link>
                <NaviMenu />
              </div>
              <Separator />
            </header>

            {/* main scroll area */}
            <div className="flex flex-col flex-1 items-center justify-center overflow-y-auto">
              {/* <header className="TopBar flex flex-col absolute top-0 left-0 right-0 z-10 h-12.5 w-full sticky"> */}

              <main
                className={cn(
                  "flex-1 w-full max-w-180 justify-between lg:max-w-4xl md:px-0 px-4",
                  zenKakuGothicNew.className,
                )}
              >
                {children}
              </main>
              <footer className={cn(
                  "w-full max-w-3xl justify-between lg:max-w-4xl md:px-0 px-4 mt-2",
                )}>
                <Separator />

                <div className="flex flex-col justify-between items-center w-full">
                  <div className="flex py-2">
                    <div>test footer</div>
                  </div>
                </div>
              </footer>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}

const NaviMenu = () => {
  return (
    <>
      {/* link list */}
      <div className="ml-auto items-center gap-4 hidden md:flex">
        <Link href="/">
          <div>menu1</div>
        </Link>
        <Link href="/">
          <div>menu2</div>
        </Link>
        <Link href="/">
          <div>menu3</div>
        </Link>
        <Link href="/">
          <div>menu4</div>
        </Link>
        <Link href="/">
          <div>menu5</div>
        </Link>
      </div>

      {/* hamburger menu */}
      <div className="ml-auto items-center gap-10 flex md:hidden">
        <DropdownMenu>
          <DropdownMenuTrigger
            render={
              <Button data-slot="dropdown-menu-trigger" variant="outline">
                <Menu />
                {/* Menu */}
              </Button>
            }
          ></DropdownMenuTrigger>
          <DropdownMenuContent
            className={`md:hidden block ${limelight.className}`}
          >
            <DropdownMenuGroup>
              {/* <DropdownMenuLabel>My Account</DropdownMenuLabel> */}
              <DropdownMenuItem>
                <Link href="/" className="w-full">
                  <div>menu1</div>
                </Link>
              </DropdownMenuItem>
              <DropdownMenuItem>
                <Link href="/" className="w-full">
                  <div>menu2</div>
                </Link>
              </DropdownMenuItem>
              {/* </DropdownMenuGroup> */}
              {/* <DropdownMenuSeparator /> */}
              {/* <DropdownMenuGroup> */}
              <DropdownMenuItem>
                <Link href="/" className="w-full">
                  <div>menu3</div>
                </Link>
              </DropdownMenuItem>
              <DropdownMenuItem>
                <Link href="/" className="w-full">
                  <div>menu4</div>
                </Link>
              </DropdownMenuItem>
            </DropdownMenuGroup>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
    </>
  );
};
